services:
  openvpn:
    image: kylemanna/openvpn
    restart: always
    ports:
      - "81194:1194/udp"
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
