services:
  openvpn:
    build: .
    restart: always
    ports:
      - "11194:1194/udp"
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    environment:
      - SERVER_NAME=${SERVER_NAME:-vpn.example.com}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
